# Generated by Django 3.2.8 on 2021-10-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0003_auto_20211016_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='assets'),
        ),
    ]
