# Generated by Django 3.2.8 on 2021-10-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0004_auto_20211016_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ad',
            name='owner_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ad',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
