# Generated by Django 3.2.8 on 2021-10-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0005_auto_20211017_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
