# Generated by Django 3.2.8 on 2021-10-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0006_auto_20211017_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
