# Generated by Django 3.2.8 on 2021-10-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0007_alter_ad_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('emailid', models.EmailField(max_length=200)),
                ('phone_no', models.BigIntegerField()),
            ],
        ),
    ]
